import Header from '@/components/header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ConvexClientProvider from './providers/ConvexClientProvider'
import { Toaster } from '@/components/ui/toaster'
import { Footer } from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster />
          <Header />
          <main
            style={{
              height: 'calc(100vh - 74px)',
            }}
          >
            {children}
          </main>
          <Footer />
        </ConvexClientProvider>
      </body>
    </html>
  )
}
